INSERT INTO springs (name, description, image_url, zipcode, fees, pets, statepark, camping, scuba, lat, lng)
VALUES ('Wekiwa Springs State Park', 'Wekiwa Springs State Park is a 7,000-acre Florida State Park in Apopka, Florida. With emerald springs feeding the Wekiwa River and lush tropical hammocks, this unique park just minutes from downtown Orlando is perfect for observing abundant wildlife or cooling off on a summer day', './Assets/images/Wekiwa-Springs-State-Park-FL.jpg', 32712, "$6/car", false, true, true, false, 28.711243, -81.463754),
('Fanning Springs State Park','Fanning Springs State Park is a Florida State Park located in Fanning Springs, Florida. The park is home to Fanning Springs, a first magnitude spring and a popular destination for swimming, snorkeling, and scuba diving.','./Assets/images/Fanning-Springs.jpg', 32693, "$6/car", false, true, true, false, 29.5905, -82.9325),
('Manatee Springs State Park','Manatee Springs State Park is a Florida State Park located in Chiefland, Florida. The park is home to Manatee Springs, a first magnitude spring and a popular destination for swimming, snorkeling, and scuba diving.','./Assets/images/Manatee-Spring-State.jpg', 32626, "$6/car",false, true, true, false, 29.4975, -82.9758),
('Weeki Wachee Springs State Park', 'Weeki Wachee Springs State Park is a Florida State Park located in Weeki Wachee, Florida. The park is home to Weeki Wachee Springs, a first magnitude spring and a popular destination for swimming, snorkeling, and scuba diving. The park is also known for its live mermaid shows.','./Assets/images/Weeki-Wachee-Springs.jpg' 34606, "$6/car", false, true, true, false, 28.5179, -82.5747),
('Silver Springs State Park', 'The 4,000-acre Silver Springs State Park encompasses not only the springs, but the entire 5-mile Silver River and surrounding sandhill forest.', './Assets/images/Silver-Springs.jpg', 34488, "$8/car", false, true, true, false, 29.2165, -82.0570),
('Rainbow Springs State Park is a Florida State Park located on the southwest side of Dunnellon, Florida. The park includes the Rainbow River, a popular destination for swimming, snorkeling, and scuba diving.', './Assets/images/Rainbow-Springs-Park.jpeg', 34432, "$2/person", false, true, true, true, 29.1023, -82.4379),
('Rock Springs Run State Reserve', 'Rock Springs Run State Reserve is a 6,000-acre Florida State Park located in Sorrento, Florida. The park is home to the largest spring on the Wekiva River, Rock Springs, which flows into the Wekiva River.', './Assets/images/Rock-Springs-Reserve.jpg', 32776, "$5/car", false, true, true, true, 28.7950, -81.4527),
('Ichetucknee Springs State Park', 'Green space with river tubing in the summer', './Assets/images/Ichetucknee-Blue-Hole.jpg', 32038, "$6/car", false, true, false, true, 29.9911, -82.7590),
('Madison Springs', 'State park in North Florida with a spring.' './Assets/images/Madison-Blue-Spring.jpg', 34606, "$6/car", false, true, false, true, 30.4813, -83.2448),
('Royal Springs', 'Spring feeds the Suwanee river.  There is a 20ft. high diving platform above the spring. Picnic area in the park.  A couple rope swings along the river.', './Assets/images/Royal-Springs.jpg', 34606, "free", false, false, false, false, false, 30.0842, -83.0747),
("Bobs River Place", "Bob's is a swimming hole on the Suwanee river.  It has slides, platforms and swings, among other activities.  Bob recently passed away, and the family is trying to get the place up and running for the 2023 season", './Assets/images/Bobs-River-Place.jpg', 32008, "free", false, false, false, false, 29.7932, -82.9238),
('Ginnie Springs', 'Ginnie Springs is a privately owned recreational park located in High Springs, Florida. The park is popular for scuba diving, swimming, and snorkeling, and is home to several underwater caves.', './Assets/images/Ginnie-Springs.jpg', 32643, "$3/person", false, false, true, true, 29.8343, -82.7024),
('Blue Spring State Park', "Blue Spring State Park is a Florida State Park located west of Orange City, Florida. The park is home to a first magnitude spring, which is the largest spring on the St. Johns River and a popular destination for swimming and manatee watching.", './Assets/images/Blue-Spring-State.jpg', 32763, "$6/car", false, true, true, false, 28.9480, -81.3370),
('DeLeon Springs State Park', 'DeLeon Springs State Park is a Florida State Park located in DeLeon Springs, Florida. The park is home to DeLeon Springs, a first magnitude spring and a popular destination for swimming, snorkeling, and scuba diving.', './Assets/images/DeLeon-Springs.jpg', 32130, "$6/car", false, true, true, false, 29.1354, -81.3621)

